authentik:
    secret_key: "<authentik-app:secret:authentik-app:secret_key>"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: false
    postgresql:
        password: "<authentik-app:secret:authentik-app:postgresql_password>"

server:
    ingress:
        enabled: false

postgresql:
    enabled: true
    auth:
        password: "<authentik-app:secret:authentik-app:postgresql_password>"
redis:
    enabled: true
