apiVersion: v1
kind: ConfigMap
metadata:
  name: glance
  namespace: glance
data:
  glance.yml: |
    branding:
      custom-footer: |
        <p>Visit my Website <a href="https://bacherik.de">here</a></p>
      logo-url: https://avatars.githubusercontent.com/u/75324423?v=4
      favicon-url: https://avatars.githubusercontent.com/u/75324423?v=4
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar
              - type: clock
                hour-format: 24h
                timezones:
                  - timezone: Europe/London
                    label: London
                  - timezone: America/Chicago
                    label: 	Minnesota
                  - timezone: America/Denver
                    label: Denver
              - type: rss
                limit: 100
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://xkcd.com/rss.xml
                  - url: http://www.turnoff.us/feed.xml
                  - url: https://samwho.dev/rss.xml
                  - url: https://www.reddit.com/r/softwaregore.rss
                    title: SoftwareGore SubReddit
                  - url: https://programming.dev/feeds/c/programmer_humor.xml?sort=New
                    title: Programming.Dev
                  - url: https://lemmy.ml/feeds/c/programmerhumor.xml?sort=New
              - type: twitch-channels
                channels:
                  - TheJoCraft_live
                  - BastiGHG
                  - BachErik_live
                  - derBanko
                  - secschool
                  - nikoverflow
          - size: full
            widgets:
              - type: hacker-news
              - type: videos
                channels:
                  - UCnqq0B0j3ySKg9G1GM-WfIQ # BachErik
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UC2Xd-TjJByJyK2w1zNwY0zQ # Beyond Fireship
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCdC0An4ZPNr_YiFiYoVbwaw # Daily Dose Of Internet
                
          - size: small
            widgets:
              - type: markets
                markets:
                  - symbol: INTC
                    name: Intel
                  - symbol: SPY
                    name: S&P 500
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: GOOGL
                    name: Google
                  - symbol: AMD
                    name: AMD
                  - symbol: RDDT
                    name: Reddit
