apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: haste-server
  namespace: haste-server
  labels:
    app: haste-server
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 1000}
      - setWeight: 60
      - pause: {duration: 1000}
      - setWeight: 80
      - pause: {duration: 1000}
      - setWeight: 90
      - pause: {}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: haste-server
  template:
    metadata:
      labels:
        app: haste-server
    spec:
      containers:
      - name: haste-server
        image: bacherik/haste-server:latest
        ports:
        - containerPort: 7777
        env:
        - name: STORAGE_TYPE
          value: redis
        - name: STORAGE_HOST
          value: haste-redis
        - name: STORAGE_PORT
          value: "6379"
        - name: PORT
          value: "7777"
        volumeMounts:
        - name: haste-data
          mountPath: /data
      volumes:
      - name: haste-data
        persistentVolumeClaim:
          claimName: haste-data-pvc
