apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haste-server
  namespace: haste-server
  annotations:
    gethomepage.dev/description: Hastebin/Pastebin fork
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Self-Hosted
    gethomepage.dev/icon: https://haste.bacherik.de/favicon.ico
    gethomepage.dev/name: Haste-server
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - haste.bacherik.de
    secretName: haste-server-tls
  rules:
  - host: "haste.bacherik.de"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haste-server
            port:
              number: 80