apiVersion: v1
kind: Service
metadata:
  name: qemu
spec:
  type: NodePort
  selector:
    name: qemu
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006
      nodePort: 30006