apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-download
  annotations:
    configmap.reloader.stakater.com/reload: "nginx-download"
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: <nginx-download:configmap:nginx-download:nginx_download_replicas>
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bacherik/filedownload:v1.0.0
        ports:
        - containerPort: 80
