apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma
  namespace: uptimekuma
  labels:
    app.kubernetes.io/name: uptimekuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uptimekuma
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uptimekuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1.23.13
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc