apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  labels:
    app.kubernetes.io/name: uptime-kuma
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - secretName: uptime-kuma-bacherik-de-tls
      hosts:
        - status.bacherik.de
  rules:
    - host: "status.bacherik.de"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3000
