apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma
  namespace: uptimekuma
  labels:
    app.kubernetes.io/name: uptimekuma
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - secretName: uptime-kuma-bacherik-de-tls
      hosts:
        - sync.bacherik.de
  rules:
    - host: "sync.bacherik.de"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: uptimekuma
                port:
                  number: 3001