apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma
  namespace: uptimekuma
  labels:
    app.kubernetes.io/name: uptimekuma
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16"
spec:
  tls:
    - secretName: uptime-kuma-<uptimekuma:configmap:test-config:subdomain>-bacherik-de-tls
      hosts:
        - <uptimekuma:configmap:test-config:subdomain>.bacherik.de
  rules:
    - host: "<uptimekuma:configmap:test-config:subdomain>.bacherik.de"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: uptimekuma
                port:
                  number: 3001
