apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  sources:
    - repoURL: "https://charts.goauthentik.io"
      chart: authentik
      targetRevision: 2024.4.2
      helm:
        version: v3
        releaseName: authentik
        valueFiles:
          - https://raw.githubusercontent.com/NikOverflow/argocd-test/master/argocd/apps/authentik-values.yml
    #- repoURL: "https://github.com/NikOverflow/argocd-test.git"
      #targetRevision: HEAD
      #ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PruneLast=true
      - PrunePropagationPolicy=foreground
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - authentik.secschool.net
    secretName: authentik-tls
  rules:
  - host: "authentik.secschool.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentik-server
            port:
              number: 80
