apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
  sources:
    - chart: authentik
      repoURL: "https://charts.goauthentik.io"
      targetRevision: 2024.4.2
      helm:
        valueFiles:
          - $values/argocd/apps/authentik-values.yml
    - repoURL: "https://github.com/NikOverflow/argocd-test.git"
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PruneLast=true
      - PrunePropagationPolicy=foreground
