apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx-download
  labels:
    app.kubernetes.io/name: nginx-download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
