apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: git-repo-sync
        image: alpine/git
        command: ['sh', '-c', '''
          git clone https://github.com/BachErik/argocd-test.git /tmp/repo && \
          find /tmp/repo/argocd/nginx-download/fileshare -type f -name "*.zip" -exec unzip -o -d /var/www/html {} \;
          ''']
        volumeMounts:
        - mountPath: "/var/www/html"
          name: nginx-me-system-storage
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/var/www/html"
          name: nginx-me-system-storage
      volumes:
      - name: nginx-me-system-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
