apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-downloader
  labels:
    app.kubernetes.io/name: nginx-downloader
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-downloader
