{{- range $key, $val := .Values.applications }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}-app
  namespace: argocd
  annotations:
    configmap.reloader.stakater.com/reload: "nginx-download"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $key }}
  sources:
    {{- range $source := $val.sources }}
    {{- if $source.chart }}
    - chart: {{ $source.chart }}
      targetRevision: {{ $source.version }}
      {{- if $source.values }}
      plugin:
        name: kph-plugin-helm
        env:
          - name: "HELM_ARGS"
            value: "-f https://raw.githubusercontent.com/BachErik/argocd-test/master/argocd/{{ $key }}-app/values.yml"
      {{- end }}
    {{- else }}
    - path: argocd/{{ $key }}-app/
      targetRevision: {{ $source.revision }}
    {{- end }}
      repoURL: {{ $source.url }}
    {{- end }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
{{- end }}
{{- end }}
